Por definición de valores y vectores propios tenemos que



$(A-λI)v=\vec{0}$

Dónde $A$ es una matriz $n\times n$, $\lambda$ es el valor propio, $v$ el vecor propio al que esta ligado el valor porpio, $I$ la matriz identidad y $\vec{0}$ el vector nulo en $\mathbb{R}^n$.

Aqui para que haya soluciones no nulas es necesario que
 $Det(A−λI)=0$ pues de lo contrario la matriz será invertible y por tanto las unicas soluciones serán triviales.


Con esto claro tenemos que al expandir $Det(A−λI)=0$ se obtiene un polinomio de grado $n$ cuya incognita es λ, el cual conocemos como polinomio caracteristico, al hayar los ceros del polinomio estamos hayando posibles valores propios y al reemplazar estos en $(A−λI)v=\vec{0}$ y despejando el vector $v$ podremos hayar el vector propio ligada a este valor propio.

Aunque el polinomio característico ofrece una forma de calcular los valores propios, resolver directamente las raíces del polinomio no es factible para matrices grandes. Por lo tanto, se aplican métodos iterativos como el método de Newton para encontrar aproximaciones a los valores propios.

## supuestos para la convergencia con el metodo de Newton

###Suposición Inicial:
 El método requiere una suposición inicial que esté razonablemente cerca de la raíz real (valor propio). Las malas suposiciones iniciales pueden resultar en una convergencia lenta o divergente.

###No Singularidad de la Matriz:
El método de Newton asume que la derivada \( p_A'(\lambda) \) no es cero en el valor propio. Si el valor propio tiene multiplicidad mayor que 1, el método puede fallar a menos que se modifique para manejar tales casos.

###Valores Propios Distintos:
El método de Newton funciona mejor para matrices con valores propios distintos. Si la matriz tiene múltiples valores propios con alta multiplicidad, la convergencia puede ser lenta o inestable sin modificaciones al método.

###Polinomios con Raíces Simples:
El método de Newton generalmente asume que las raíces del polinomio característico son simples (no repetidas). Para raíces repetidas, se suelen usar algoritmos especializados como deflación o técnicas shift-invert para mejorar la convergencia.

Con todas estas suposiciones, según "Numerical Analysis" de Burden y Faires pagina 84 podemos afirmar que el polinomio será cuadraticamente convergente, es decirque existe una constante $C>0$ tal que $\left| x_{k+1} - x^* \right| \leq C \left| x_k - x^* \right|^2$ para cada iteración del metodo.

#Codigo y test


In [3]:
import numpy as np

# Function to compute eigenvalues and eigenvectors of a matrix
def compute_eigen(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    # Force eigenvalues and eigenvectors to be real if the imaginary part is negligible
    eigenvalues = eigenvalues.real  # Remove imaginary part completely
    eigenvectors = eigenvectors.real  # Remove imaginary part completely
    return eigenvalues, eigenvectors

# Function to compute the characteristic polynomial of a matrix
def characteristic_polynomial(matrix):
    return np.poly(matrix)

# Compute the error for eigenvalues and eigenvectors
def compute_error(matrix, eigenvalues, eigenvectors):
    max_error = 0
    for i, eigenvalue in enumerate(eigenvalues):
        vec = eigenvectors[:, i]
        error = np.linalg.norm(matrix @ vec - eigenvalue * vec)
        max_error = max(max_error, error)
    return max_error

# Define a function to display results clearly for a single matrix
def display_results_for_matrix(matrix, matrix_name):
    eigenvalues, eigenvectors = compute_eigen(matrix)
    char_poly = characteristic_polynomial(matrix)
    max_error = compute_error(matrix, eigenvalues, eigenvectors)

    # Format the results nicely
    print(f"\nResults for Matrix {matrix_name}:")
    print(f"Matrix:\n{matrix}\n")
    print("Characteristic Polynomial:")
    print(" + ".join([f"{coeff:.3f}x^{len(char_poly)-i-1}" for i, coeff in enumerate(char_poly) if coeff != 0]).replace("x^0", ""))
    print("\nEigenvalues:")
    print(", ".join([f"{val:.3f}" for val in eigenvalues]))

    # Format eigenvectors nicely
    print("\nEigenvectors:")
    for i in range(eigenvectors.shape[1]):
        print(f"Eigenvector {i+1}: [{', '.join([f'{v:.3f}' for v in eigenvectors[:, i]])}]")

    print(f"\nMax Error: {max_error:.2e}")
    print("-" * 50)

# Define matrices as provided
matrices = {
    "A": np.array([[2, 1], [3, 4]]),
    "B": np.array([[3, 2], [3, 4]]),
    "C": np.array([[2, 3], [1, 4]]),
    "D": np.array([[1, 1, 2], [2, 1, 1], [1, 1, 3]]),
    "E": np.array([[1, 1, 2], [2, 1, 3], [1, 1, 1]]),
    "F": np.array([[2, 1, 2], [1, 1, 3], [1, 1, 1]]),
    "G": np.array([[1, 1, 1, 2], [2, 1, 1, 1], [3, 2, 1, 2], [2, 1, 1, 4]]),
    "H": np.array([[1, 2, 1, 2], [2, 1, 1, 1], [3, 2, 1, 2], [2, 1, 1, 4]]),
}

# Display results for each matrix one by one
for name, matrix in matrices.items():
    display_results_for_matrix(matrix, name)



Results for Matrix A:
Matrix:
[[2 1]
 [3 4]]

Characteristic Polynomial:
1.000x^2 + -6.000x^1 + 5.000

Eigenvalues:
1.000, 5.000

Eigenvectors:
Eigenvector 1: [-0.707, 0.707]
Eigenvector 2: [-0.316, -0.949]

Max Error: 0.00e+00
--------------------------------------------------

Results for Matrix B:
Matrix:
[[3 2]
 [3 4]]

Characteristic Polynomial:
1.000x^2 + -7.000x^1 + 6.000

Eigenvalues:
1.000, 6.000

Eigenvectors:
Eigenvector 1: [-0.707, 0.707]
Eigenvector 2: [-0.555, -0.832]

Max Error: 0.00e+00
--------------------------------------------------

Results for Matrix C:
Matrix:
[[2 3]
 [1 4]]

Characteristic Polynomial:
1.000x^2 + -6.000x^1 + 5.000

Eigenvalues:
1.000, 5.000

Eigenvectors:
Eigenvector 1: [-0.949, 0.316]
Eigenvector 2: [-0.707, -0.707]

Max Error: 5.55e-17
--------------------------------------------------

Results for Matrix D:
Matrix:
[[1 1 2]
 [2 1 1]
 [1 1 3]]

Characteristic Polynomial:
1.000x^3 + -5.000x^2 + 2.000x^1 + 1.000

Eigenvalues:
4.507, -0.285, 0.77