In [151]:
import numpy as np
np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)

# Algoritmo QR

Sea $A$ una matriz $n \times n$. Supongamos que $A$ es no singular, y que sus autovalores cumplen que $|\lambda_1| > |\lambda_2| > ... > |\lambda_n|$. Nuestro objetivo es encontrar los autovalores de $A$. Notemos que si encontramos una matriz $\tilde{A}$ triangular superior, tal que $\tilde{A}$ es similar a $A$, entonces hemos acabado, pues $\tilde{A}$ tiene los mismos autovalores de $A$, y como $\tilde{A}$ es triangular superior, sus autovalores aparecen en la diagonal, ya que el  polínomio característico es $p(x) = (x - a_1)(x - a_2)...(x - a_n)$, con los $a_i$ los elementos de la diagonal. Con base en lo anterior, enfoquemos nuestros esfuerzos en encontrar una aproximación a una matriz diagonal $\tilde{A}$ similar a $A$. 

Sean $v_1, ..., v_n$ los autovectores de $A$ ordenados con respecto al orden decreciente de sus autovalores, y sea $T_k  = gen(v_1, ... v_k)$.  Supongamos que $Q = [Q_1Q_2]$ es una matriz ortogonal cuyas primeras $k$ columnas $(Q_1)$ forman una base ortogonal para el subespacio $T_k$. Entonces

$$Q^TAQ =
\begin{bmatrix}
Q_1^TAQ_1 & Q_1^TAQ_2 \\
Q_2^TAQ_1 & Q_2^TAQ_2
\end{bmatrix}=
\begin{bmatrix}
A_{11} & A_{12} \\
0 & A_{22}
\end{bmatrix}, \quad (1)$$

donde $Q_2^{T}AQ_1 = 0$ pues $T$ es invariante. La matriz anterior es una matriz triangular superior por bloques. Notemos que si $k = 1$, entonces el bloque $A_{11}$ tiene dimensión $1 \times 1$. Se sigue que la primera columna tiene ceros excepto en la primera entrada de $Q^T A Q$, la cual es un autovalor de $Q^T A Q$, y por similaridad es un autovalor de $A$.  Si  se cumple simultáneamente que la primera columna forma una base ortogonal para $gen(v_1)$, y que las dos primeras columnas forman una base ortogonal para $gen(v_1, v_2)$, (esto es, $k = 2$), entonces la primera columna tiene ceros excepto en la primera entrada, y la segunda columna tiene ceros excepto en la primera y segunda entrada, pues se sigue respetando la forma $(1)$, donde el bloque $A_{11}$ tiene tamaño $2 \times 2$, y por lo tanto el bloque inferior es de ceros. Si se cumplieran simultáneamente los casos $k = 1$, $k = 2$, ... $k = n$, entonces la matriz $Q^TAQ$ sería una matriz triangular superior, pues la forma $(1)$ se está cumpliendo simultáneamente para cada $k$.  Por lo tanto, hemos reducido el problema de encontrar una matriz triangular superior $\tilde{A}$ similar a $A$, a encontrar una matriz ortogonal $Q$ tal que las primeras $k$ columnas formen una base para $gen(v_1, ..., v_k)$, $1 \leq k \leq n$. 

Recordemos que el método de potencias consiste en escoger un vector $v$ y aplicarle $A$ repetidamente para formar la sucesión

$$v, Av, A^2v, A^3v, ...$$

Asumiendo que se reescala adecuada el vector $v$ después de cada iteración, la sucesión usualmente convergerá a un autovector de $A$. Veamos rapidamente por qué.  Si $A$ tiene autovalores $\lambda_1$, $\lambda_2$, ..., $\lambda_n$ tales que $|\lambda_1| > |\lambda_2| \geq ... \geq |\lambda_n|$ y $n$ autovectores linealmente independientes $v_1, v_2, ..., v_n$ correspondientes a los autovalores anteriores, entonces podemos expresar $v$ como

$$v = c_1v_1 + c_2v_2 + ... + c_nv_n.$$

Luego, al aplicar $A$ repetidamente obtenemos

$$A^mv = c_1\lambda_1^mv_1 + c_2\lambda_2^mv_2 + ... + c_n\lambda_n^mv_n.$$

Como $\lambda_1$ domina a los demás autovalores, la componente en la dirección de $v_1$ eventualmente domina a las demás componentes, y por lo tanto $A^mv$ converge a un elemento del espacio $<v>$ cuando $m \rightarrow \infty$. 

Notemos que podemos ver el proceso anterior como como una iteración sobre _subespacios_: empezamos con un subespacio inicial $S =<v>$. Entonces iteramos

$$S, AS, A^2S, A^3S, ...$$

y la sucesión anterior "converge" al autoespacio $T = gen(v_1)$. Para volver rigurosa la noción anterior, definamos una métrica en el conjunto de supespacios $k$ - dimensionales de $\mathbb{R}^n$: 

$$d(S, T) = sup_{s \in S} inf_{t \in T} ||s - t ||_2,$$
    
donde $||\cdot|||_2$ es la norma Euclideana. El resultado principal de la convergencia de la iteración de subespacios es el siguiente:

*Teorema 1*
Sea $v_1$, ..., $v_n$ una base de autovectores de $A$. Sean $T = <v_1, ..., v_k>$, $U = <v_{k+1}, ..., v_n>$. Los espacios $T$ y $U$ son llamados _dominante_ y _co-dominante_, respectivamente. Sea $S$ un espacio $k$-dimensional de $\mathbb{R}^n$ tal que $S \cap U = (0)$. Entonces existe una constante $C$ tal que

$$d(A^mS, T) \leq C|\lambda_{k+1}/\lambda_{k}|^m$$

para todo $m$. Por lo tanto $A^mS \rightarrow T$ linealmente con tasa $|\lambda_{k+1}/\lambda_k|$.

Sea $q_1^{0}, ..., q_n^{0}$ una base para $S$. Entonces $A^m(q_{1}^0), ..., A^m(q_n^{0})$ es una base para $A^mS$, ya que como $A^m$ es invertible, en cada iteración seguimos obteniendo un conjunto generador y linealmente independiente. Por el teorema anterior, podemos iterar la base $q_1^{0}, ..., q_n^{0}$ con $A$ para obtener una base para $T$. Si después de cada iteración ortogonalizamos la base obtenida de izquierda a derecha, entonces la matriz $Q_m$ cuyas columnas son  $A^m(q_{1}^0), ..., A^m(q_n^{0})$ sería una matriz ortogonal cuyas columnas forman una base para un espacio muy cercano a $T$. Más aún, la ortogonalización preserva la propiedad de que los primeros $k$ vectores forman una base para $gen(A^m(q_{1}^0), ..., A^m(q_k^{0})$ para cada $k$, y por lo tanto $Q_m$ converge a una matriz $Q$ ortogonal cuyas $k$ primeras columnas forman una base de $T_k = gen(v_1, ..., v_k)$ para cada $k$, que es precisamente lo que estamos buscando. 

Por lo tanto, ahora tenemos una idea para obtener el $Q$ buscado: empezamos con una base ortogonal $e_1, ..., e_n$ del espacio, y formamos una matriz $Q_0$ cuyas columnas son los elementos de esta base. A continuación calculamos $AQ_0$, y buscamos una nueva matriz $Q_1$ cuyas columnas sean la ortogonalización de las matrices de $A$. Esto es, buscamos una matriz $Q_1$ y una matriz $R_1$ tal que $A = Q_1R_1$. A continuación hacemos $AQ_1$, y buscamos matrices $Q_2R_2$ tales que $AQ_1 = Q_2R_2$. En general, definimos 

$$D_m = AQ_{m-1}$$,

 y buscamos matrices $Q_m$, $R_m$ tal que $D_m = Q_{m+1}R_{m+1}$. Verificamos la convergencia calculando $Q^{T}_mAQ_m$, y verificando que los elementos de la triangular inferior estén cerca de $0$. Una vez nos hemos acercado lo suficiente a una matriz triangular superior, recolectamos los valores en la diagonal, que corresponden a los autovalores de $A$.  Este es el algoritmo $QR$. 

Podríamos ortogonalizar usando el proceso de Graham-Schmidt. Sin embargo, en la práctica el algoritmo no es estable numericamente. Por lo tanto usaremos matrices de Householder.

## Descomposición QR

Sea $A$ una matriz real cuadrada. Entonces $A$ puede ser factorizada como 

$$ A = QR, $$

donde $Q$ es una matriz ortogonal y $R$ es una matriz triangular superior. A continuación, describiremos un método para hallar la descomposición QR de cualquier matriz cuadrada A. Sea $v \in \mathbb{R}^n$ un vector no nulo. Sea $H$ una matriz $n \times n$ de la forma

$$ H = I - 2vv^{T}.$$

Entonces $H$ es llamada una _matriz de Householder_. Llamamos a $v$ un vector de Householder. Si aplicamos $H$ a un vector $x$, este es reflejado en el hiperplano $gen(v)^{\bot}$. Es directo verificar que las matrices de Householder son simétricas y ortogonales. La utilidad de las matrices de Householder para la descomposición QR yace en el siguiente hecho: sea $x \in R^{n}$, y sea $u = x - s||x||e_{1}$. Si tomamos $v = u / ||u||$ la normalización de $u$, entonces

$$Hx = (I - 2\frac{u u^{T}}{u^{T}u})x = ||x||e_{1}$$. 

Esto es, aplicar $H$ a $x$ lo convierte en un múltiplo de $e_{1}$, con la misma magnitud de $x$. Otra forma de verlo es que hemos dejado en $0$ todas las componentes de $x$ excepto por la primera, en la que ha quedado su magnitud. Se sigue que si tomamos una sucesión adecuada de matrices de Householder $H_1, H_2, ..., H_{n-1}$ podemos convertir una matriz $A$ en una matriz triangular superior, ya que podemos ir convirtiendo en $0$ los elementos debajo de la diagonal. Veamos como podemos hacerlo con un ejemplo. Definamos una matriz A de tamaño $4 \times 4$.

In [152]:
A = np.array([[1, 0, 0, 0],
              [3, 2, 0, 0], 
              [1, 1, 4, 0],
              [1, 2, 1, 7]])

Ahora, definamos $x$ como la primera columna de la matriz

In [153]:
x = A[:, 0]
x

array([1, 3, 1, 1])

La norma de $x$ es: 

In [154]:
np.linalg.norm(x)

3.4641016151377544

Calculamos $u$, $v$ y $H$ como lo describimos anteriormente:

In [155]:
u = x - np.linalg.norm(x) * np.eye(1, 4, 0)
v = (1/np.linalg.norm(u)) *  u
H1 = np.eye(4) - 2*v*v.T
H1

array([[ 0.289,  0.866,  0.289,  0.289],
       [ 0.866, -0.054, -0.351, -0.351],
       [ 0.289, -0.351,  0.883, -0.117],
       [ 0.289, -0.351, -0.117,  0.883]])

La matriz anterior es la matriz de Householder $H_1$. Notemos que si aplicamos $H_1$ a $x$ obtenemos el siguiente arreglo:

In [156]:
H1.dot(x)

array([ 3.464, -0.   ,  0.   ,  0.   ])

Lo que nos indica que la matriz $H$ efectivamente hace lo que queremos: dejar en $0$ todas las componentes de $x$ excepto por la primera, en la que queda su magnitud. Además, el producto $HA$ es

In [157]:
H1.dot(A)

array([[ 3.464, -1.732,  1.443,  2.021],
       [-0.   , -0.891, -1.757, -2.46 ],
       [ 0.   ,  1.703,  3.414, -0.82 ],
       [-0.   ,  2.703,  0.414,  6.18 ]])

Es decir, hemos logrado poner los ceros que queríamos en la primera columna de A. Ahora, queremos poner ceros en la siguiente columna. Esto es, queremos hacerle el proceso anterior al vector $x = \begin{bmatrix}
{-2.029} \\
{-0.343} \\
{0.657} 
\end{bmatrix}$. Notemos que este vector ahora tiene $3$ componentes, pues lo que queremos es tranformar a $A$ en una matriz triangular superior, por lo que no nos interesa lo que le suceda a la primera componente. Luego, debemos operar ahora sobre la submatriz $(n - 1) \times (n - 1)$ que resulta de omitir la primera fila y la segunda columna. En nuestro ejemplo, ahora queremos operar sobre la siguiente matriz:


In [158]:
sub_matrix1 = H1.dot(A)[1:, 1:]
sub_matrix1

array([[-0.891, -1.757, -2.46 ],
       [ 1.703,  3.414, -0.82 ],
       [ 2.703,  0.414,  6.18 ]])

Como habíamos hecho antes, ahora definamos $x_2$ como la primera columna de la matriz anterior, y calculemos la matriz $H_2$ correspondiente.

In [159]:
x2  = sub_matrix1[:, 0]
u2 = x2 - np.linalg.norm(x2) * np.eye(1, 3, 0) 
v2 = (1/np.linalg.norm(u2)) *  u2
H2 = np.eye(3) - 2*v2*v2.T
H2

array([[-0.269,  0.513,  0.815],
       [ 0.513,  0.792, -0.33 ],
       [ 0.815, -0.33 ,  0.477]])

Recordemos que las matrices $A$ y $H_1A$ son matrices $4 \times 4$. Sin embargo nuestra $H_2$ actual es una matriz $3 \times 3$, pues esta en principio solo debía operar en una submatriz de $HA$. Arreglamos este problema introduciendo un padding a la matriz $H_2$, de tal manera que la primera fila y la primera columna de $H_2$ sean el vector $e_1$. Esto no afecta la ortogonalidad ni la simetría de $H_2$. 

In [160]:
e1 = np.array([1, 0, 0, 0])

H_padded = np.zeros((4, 4))

H_padded[0, :] = e1  
H_padded[:, 0] = e1  

H_padded[1:, 1:] = H2

H2 = H_padded
H2

array([[ 1.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   , -0.269,  0.513,  0.815],
       [ 0.   ,  0.513,  0.792, -0.33 ],
       [ 0.   ,  0.815, -0.33 ,  0.477]])

Ahora calculamos $H_2H_1A$: 

In [161]:
H2.dot(H1).dot(A)

array([[ 3.464, -1.732,  1.443,  2.021],
       [-0.   ,  3.317,  2.563,  5.276],
       [ 0.   ,  0.   ,  1.666, -3.951],
       [-0.   ,  0.   , -2.361,  1.21 ]])

Siguiendo el mismo proceso anterior, obtenemos una matriz $H_3$

In [162]:
sub_matrix2 = H2.dot(H1).dot(A)[2:, 2:]
x3  = sub_matrix2[:, 0]
u3 = x3 - np.linalg.norm(x3) * np.eye(1, 2, 0) 
v3 = (1/np.linalg.norm(u3)) *  u3
H3 = np.eye(2) - 2*v3*v3.T

#Le hacemos el padding
e1 = np.array([1, 0, 0, 0])
e2 = np.array([0, 1, 0, 0])

H_padded = np.zeros((4, 4))

H_padded[0, :] = e1  
H_padded[:, 0] = e1  

H_padded[1, :] = e2  
H_padded[:, 1] = e2  

H_padded[2:, 2:] = H3

H3 = H_padded
H3

array([[ 1.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  1.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.577, -0.817],
       [ 0.   ,  0.   , -0.817, -0.577]])

Notemos que por construcción $H_3H_2H_1A$ debe ser una matriz triangular superior $R$. En efecto:

In [163]:
R = H3.dot(H2).dot(H1).dot(A)
R

array([[ 3.464, -1.732,  1.443,  2.021],
       [-0.   ,  3.317,  2.563,  5.276],
       [ 0.   , -0.   ,  2.889, -3.267],
       [ 0.   , -0.   ,  0.   ,  2.53 ]])

Como $H_1$, $H_2$ y $H_3$ son ortonogales, si definimos $Q = (H_3H_2H_1)^T$, entonces $Q = H_1^{T}H_2^{T}H_{3}^T = H_1^{-1}H_2^{-1}H_3^{-1}$, y por lo tanto $Q(H_3H_2H_1A) = QR = A$. Esto es, hemos encontrado la descomposición $QR$ de $A$. Lo comprobamos en el ejemplo:

In [164]:
Q = (H3.dot(H2).dot(H1)).T
print('Matriz A: ')
print(A)

print('\nMatriz QR: ')
print(Q.dot(R))

Matriz A: 
[[ 1  0  0  0]
 [ 3 -3  0  0]
 [ 1  1  4  0]
 [ 1  2  1  7]]

Matriz QR: 
[[ 1.  0.  0.  0.]
 [ 3. -3.  0.  0.]
 [ 1.  1.  4. -0.]
 [ 1.  2.  1.  7.]]


El anterior era solo un ejemplo ilustrativo. En la práctica se realizan cosas extras para llegar más eficientemente a la descomposición. Por ejemplo, para almacenar las matrices de Householder $H_i$ no necesitamos guardar toda la matriz, sino solo el vector de Householder $v$. 

Recordemos que nuestro objetivo es encontrar los autovalores de $A$. A continuación, realizaremos unas observaciones que nos llevaran intuitivamente (pero también rigurosamente) al algoritmo QR. 

# Análisis del error

Por el teorema de la convergencia de subespacios, $A^mS$ converge a T con tasa $C|\lambda_{k+1} / \lambda_k|$. Se sigue que el algoritmo converge a una matriz triangular superior a esta tasa. Es posible modificar el algoritmo (con shifts) para lograr una convergencia mucho más rápida a los autovalores.  

# Implementación 

A continuación presentamos implementaciones para calcular la descomposición $QR$, y otro para calcular la matriz triangular superior $\tilde{A}$ que permite recolectar los autovalores de $A$.  
### householder_qr()

Es una implementación generalizada del proceso anterior para encontrar la descomposición $QR$ a través de matrices de Householder.  

In [165]:
def householder_qr(A):
    """"
    
    Parametros
    A: Matriz a descomponer
    
    Returna:
    tupla: (Q, R) donde Q es matriz ortogonal y R es matriz triangular superior
    """
    
    A = np.array(A, dtype=float)
    m, n = A.shape
    Q = np.eye(m)
    R = A.copy()
    
    # Itera cada columna
    for j in range(min(m-1, n)):
        # Extraemos la columna en la que estamos trbajando
        x = R[j:, j]
        
        # Calculamos el vector de householder
        e1 = np.zeros_like(x)
        e1[0] = 1
        
        alpha = -np.sign(x[0]) * np.linalg.norm(x) # Multiplicamos por el signo para estabilidad
                                                   # numérica
        u = x - alpha * e1
        v = u / np.linalg.norm(u)
        H = np.eye(m)
        H[j:, j:] -= 2.0 * np.outer(v, v)
        R = H @ R
        Q = Q @ H.T # Vamos acumulando Q
    
    # Ponemos ceros en la triangular inferior para asegurar que es triangular superior
    for i in range(m):
        for j in range(i):
            if j < n:
                R[i, j] = 0.0
    
    return Q, R


In [166]:
A

array([[ 1,  0,  0,  0],
       [ 3, -3,  0,  0],
       [ 1,  1,  4,  0],
       [ 1,  2,  1,  7]])

In [167]:
Q, R = householder_qr(A)
Q @ R

array([[ 1., -0., -0., -0.],
       [ 3., -3.,  0.,  0.],
       [ 1.,  1.,  4., -0.],
       [ 1.,  2.,  1.,  7.]])

### qr_eigenvalue_algorithm()

El siguiente código calcula el algoritmo $QR$, mediante el procedimiento descrito anteriormente. Además, se hace uso de la siguiente observación:

Para $A_1 = A_1I$, esta tiene una descomposición

$$A_1 = Q'_2R'_2.$$

Luego $Q'^T_2A_1 = R'_2$. Por definición, $A_1 = Q_1^{T}AQ_1$,  $D_1 = AQ_1$, y $D_1$ tiene una descomposición $Q_2R_2$. Se sigue que

$$Q_2R_2 = D_1 = AQ_1 = Q_1A_1Q_1^TQ_1 = Q_1A_1 = Q_1Q'_2R'_2.$$

Ahora, es un hecho que la descomposición $QR$ es única si $A$ se escoge invertible, y $R$ con diagonal positiva. Por lo tanto $Q_2 = Q_1Q_2', R_2 = R_2'$ y así

$$A_2 = Q_2^TAQ_2 = Q_2'^TQ_1^TAQ_1Q_2' = Q_2^TA_1Q'_2 = R_2'Q_2'. $$

Ahora para calcular $A_3$, basta calcular la descomposición $Q_3R_3$ de $A_2$, y hacer $A_3 = R_3Q_3$. La siguiente implementación usa esta idea para calcular matrices triangulares $A_m$.




In [168]:
def qr_eigenvalue_algorithm(A, max_iter=1000, tolerance=1e-10):
    
    """
    Computa autovalores usando el algoritmo QR
    
    Parameters:
    A (list): Matriz a la que se hallarán los autovalores
    max_iter (int): Número máximo de iteraciones
    tolerance (float): Tolerancia de la convergencia
    
    Returna:
    np.array: eigenvalues
    """
    
    A = np.array(A, dtype=float)
    n = A.shape[0]
    V = np.eye(n)
    H = A.copy()
    
    for _ in range(max_iter):
        
        Q, R = householder_qr(H)
        H = R @ Q
        V = V @ Q
        
        off_diag_norm = np.sum(np.abs(np.tril(H, -1))) #Calcula norma de diagonal debajo de la diagonal principal.
        
        if off_diag_norm < tolerance: #Con base en el valor anterior, verificamos la convergencia del método
            break
    
    eigenvalues = np.diag(H)
    
    return eigenvalues
    

In [169]:
qr_eigenvalue_algorithm(A)

array([ 7.,  4., -3.,  1.])

# Ejemplo

Calculamos los autovalores de las siguientes matrices dadas en la tarea:

In [170]:
A = np.array([[2, 1], 
              [3, 4]])

B = np.array([[3, 2],
              [3, 4]])

C = np.array([[2, 3],
              [1, 4]])

D = np.array([[1, 1, 2],
              [2, 1, 1], 
              [1, 1, 3]])

E = np.array([[1, 1, 2],
              [2, 1, 3],
              [1, 1, 1]])

F = np.array([[2, 1, 2], 
              [1, 1, 3],
              [1, 1, 1]])

G = np.array([[1, 1, 1, 2],
              [2, 1, 1, 1],
              [3, 2, 1, 2],
              [2, 1, 1, 4]])

H = np.array([[1, 2, 1, 2],
              [2, 1, 1, 1], 
              [3, 2, 1, 2],
              [2, 1, 1, 4]])

In [172]:
print(f'Los autovalores de A son: {qr_eigenvalue_algorithm(A)}\n')
print(f'Los autovalores de B son: {qr_eigenvalue_algorithm(B)}\n')
print(f'Los autovalores de C son: {qr_eigenvalue_algorithm(C)}\n')
print(f'Los autovalores de D son: {qr_eigenvalue_algorithm(D)}\n')
print(f'Los autovalores de E son: {qr_eigenvalue_algorithm(E)}\n')
print(f'Los autovalores de F son: {qr_eigenvalue_algorithm(F)}\n')
print(f'Los autovalores de G son: {qr_eigenvalue_algorithm(G)}\n')
print(f'Los autovalores de H son: {qr_eigenvalue_algorithm(H)}\n')

Los autovalores de A son: [5. 1.]

Los autovalores de B son: [6. 1.]

Los autovalores de C son: [5. 1.]

Los autovalores de D son: [ 4.507  0.778 -0.285]

Los autovalores de E son: [ 4.049 -0.692 -0.357]

Los autovalores de F son: [ 4.125 -0.762  0.637]

Los autovalores de G son: [ 6.635  1.509 -0.736 -0.407]

Los autovalores de H son: [ 6.827  1.728 -1.088 -0.467]



Vemos que logramos obtener los autovalores de cada matriz. Las ventajas del método es que su implementación es sencilla, y que tenemos un resultado fuerte para la tasa de convergencia a una matriz triangular. El método presenta problemas cuando la matriz tiene autovalores con igual módulo, pues en este caso no converge a una matriz triangular superior, aunque igualmente se puede obtener información de los autovalores de la matriz. También el caso en el que el módulo de los autovalores es muy cercano presenta problemas. 

El caso en el que $A$ es no invertible no es tan patológico como parece: en una iteración, el autovalor $0$ se quita en la primera iteración, y el algoritmo sigue operando como si fuera una matriz no singular. 